site_name: Study Decks
site_url: https://rajdyp.github.io/study-decks/

nav:
  - Home: index.md
  - Python:
    - Fundamentals:
      - Python Basics:
        - Python Basics: python/fundamentals/python_basics.md
        - Exercises: python/fundamentals/python_basics_exercises.md
      - Modules:
        - Modules: python/fundamentals/modules.md
    - DSA:
      - Arrays:
        - Arrays: python/dsa/arrays.md
      - Leetcode:
        - Leetcode: python/dsa/leetcode.md

theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/rajdyp"  target="_blank" rel="noopener">Rajdeep Rai</a>
