site_name: StudyNotes
site_url: https://rajdyp.github.io/study-decks/

nav:
  - Home: index.md
  - Coding:
    - Python:
      - Fundamentals:
        - Python Basics:
          - Notes: python/fundamentals/python.md
          - Exercises: python/fundamentals/python_exercises.md
          - Quiz: python/fundamentals/python_quiz.md
        - Modules:
          - Modules: python/fundamentals/modules.md
        - Frameworks:
          - Fast API: 
            - Notes: python/fundamentals/fast_api.md
            - Ultimate FastAPI Tutorial:
              - Hello World:
                  - app:
                      - main.py: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-01-hello-world/app/main.md
                  - run.sh: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-01-hello-world/run.md
              - Path Parameters: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Query Parameters: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Pydantic Schemas: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Basic Error Handling: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Jinja Templates: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Database: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Structure And Versioning: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Async: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - JWT Auth: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Dependency Injection: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - React frontend: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Docker Deployment: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
              - Send Email in Background: python/drill-down/fastapi/ultimate-fastapi-tutorial/part-07-database/app/crud/base.md
      - DSA:
        - Arrays:
          - Arrays: python/dsa/arrays.md
        - Practice Problems:
          - Leetcode: python/dsa/leetcode.md
      - Others:
        - External Links: python/fundamentals/external_links.md
  - OS:
    - Linux:
      - Notes: linux/linux.md
      - Quiz: linux/linux_quiz.md
  - Container:
    - Docker:
      - Notes: docker/docker.md
      - CLI: docker/docker_cli.md
  - Container Orchestration:
    - Kubernetes:
      - Notes: k8s/k8s.md
      - CLI: k8s/k8s_cli.md
    - Helm:
      - Notes: helm/helm.md
  - Service Mesh:
    - Istio:
      - Notes: istio/istio.md
      - CLI: istio/istio_cli.md
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.instant
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: amber 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: amber
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    annotation: material/plus-circle

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/rajdyp"  target="_blank" rel="noopener">Rajdeep Rai</a>
